on: push
name: Deploy to nashural.ru
jobs:
  deploy-ftp:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use node 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: Build project
      run: |
        npm install --production
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: nashural.ru
        username: nashur_0
        password: ${{ secrets.ftp_password }}
        local-dir: ./build/
        server-dir: /tours/
